// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002201957_AddMenuSystem")]
    partial class AddMenuSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.HasKey("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Credits = 3,
                            Description = "Code_First Migration",
                            InstructorId = 1,
                            Title = "EFCore"
                        },
                        new
                        {
                            CourseId = 2,
                            Credits = 3,
                            Description = "Fundamentals of Physics",
                            InstructorId = 1,
                            Title = "Physics"
                        },
                        new
                        {
                            CourseId = 3,
                            Credits = 3,
                            Description = "Fundamentals of C#",
                            Title = "C#"
                        },
                        new
                        {
                            CourseId = 4,
                            Credits = 4,
                            Description = "SQL Server and Database Design",
                            InstructorId = 2,
                            Title = "Database Systems"
                        },
                        new
                        {
                            CourseId = 5,
                            Credits = 4,
                            Description = "Introduction to Programming and Problem Solving",
                            InstructorId = 3,
                            Title = "Programming"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<int?>("Grade")
                        .HasColumnType("INT");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 90
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 85
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 92
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 89
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 94
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("InstructorId");

                    b.ToTable("Instuctors", (string)null);

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            FullName = "Issam abdelnaby"
                        },
                        new
                        {
                            InstructorId = 2,
                            FullName = "Mohamed Hisham"
                        },
                        new
                        {
                            InstructorId = 3,
                            FullName = "Omar Khaled"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(2005, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mo7amed0518@gmail.com",
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mohamed Elsayed"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(2001, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.hassan@.com",
                            EnrollmentDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ahmed Hassan"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(2003, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.ali@.com",
                            EnrollmentDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Ali"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateTime(2002, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssefmohamed@gmail.com",
                            EnrollmentDate = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Youssef Mohamed"
                        },
                        new
                        {
                            StudentId = 5,
                            DateOfBirth = new DateTime(2001, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mahmoud.adel@gmail.com",
                            EnrollmentDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mahmoud Adel"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.HasOne("StudentManagementSystem.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("StudentManagementSystem.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
